In [3]:
# 计算超过200字评论的数量

In [4]:
# 调用所有评论数据库

In [1]:
import pymysql
import pandas as pd
#连接数据库
conn=pymysql.connect(host = '127.0.0.1' # 连接名称，默认127.0.0.1
,user = 'root' # 用户名
,passwd='123456' # 密码
,port= 3306 # 端口，默认为3306
,db='weibo' # 数据库名称
,charset='utf8' # 字符编码
)
cur = conn.cursor() # 生成游标对象
sql="select * from `post`  " # SQL语句
cur.execute(sql) # 执行SQL语句
data = cur.fetchall() # 通过fetchall方法获得数据
for i in data[:20]: # 打印输出前3条数据
    print(i)
# cur.close() # 关闭游标
# conn.close() # 关闭连接

(1451, '圆明园', '小桃枝枝', '2022-11-25 17:50', '明天就要降温了今天风好大', '2022-11-25 21:10:47')
(1452, '圆明园', '繁星-满空', '2022-11-25 19:29', '这样能封一辈子吗病毒没死几个人防疫倒是快把人折磨死了', '2022-11-25 21:10:47')
(1453, '圆明园', 'Ronnie-Osullivan', '2022-11-25 11:11', '圆明园被烧十二年后长春园西洋楼花园门残影摄于公元1873同治十二年', '2022-11-25 21:10:47')
(1454, '圆明园', '白雪皑皑银装素裹分外妖娆', '2022-11-25 14:55', '分享图片', '2022-11-25 21:10:47')
(1455, '圆明园', '在学术边缘挣扎', '2022-11-25 13:04', '吃完饭坐上坐骑真舒服呀', '2022-11-25 21:10:47')
(1456, '圆明园', 'Arztkhoo', '2022-11-25 00:17', '上周免费大花园秋景观赏之旅', '2022-11-25 21:10:47')
(1457, '圆明园', '星儿_薇薇子', '2022-11-24 17:48', '在这个昏沉沉的天里只有它们才是无忧无虑吧', '2022-11-25 21:10:47')
(1458, '圆明园', '鲍勃带哥', '2022-11-24 16:32', '', '2022-11-25 21:10:47')
(1459, '圆明园', '王者酷行', '2022-11-24 18:07', '好在这世上记忆是自己的', '2022-11-25 21:10:47')
(1460, '圆明园', 'w逸少', '2022-11-24 09:56', '', '2022-11-25 21:10:47')
(1461, '圆明园', '珂珂不吃肉肉', '2022-11-23 20:19', '一半惊艳一半叹息', '2022-11-25 21:10:47')
(1462, '圆明园', '萌萌哒少女是脸也是心_', '2022-11-23 20:07', '', '2022-11-25 21:10:47')
(1463, '圆明园', '榕塔纳', '2022-11-23 04:21', '库存', '2022-11-25 21:10:47')
(1464, '圆明园', '小桃枝枝', '2022-11-23 13:16', '', '2022-11-25 21:10:47')
(1465, '圆明园', '想养缅因猫06', '2022-11-23 16:03', '<br>每年冬天疫情必来一次圆明园真不希望以这种方式逛园子', '2022-11-25 21:10:47')
(1466, '圆明园', '王小虎呦', '2022-11-22 21:11', '今年秋天好长景色好美唯一值得开心点的事情了', '2022-11-25 21:10:47')
(1467, '圆明园', '天涯oz', '2022-11-22 22:29', '<br><br>周日的圆明园<br><br>周六一起出行的朋友说周日一早小区就封闭了一直关到今天还没出来关键小区里也都没测出阳性来看新闻奥森公园和朝阳公园现在也都关闭了好在海淀群众身边还有皇家园林估计能坚守到最后了', '2022-11-25 21:10:47')
(1468, '圆明园', 'Mark逍遥游', '2022-11-23 15:25', '他们越是要把生活打碎我们越是要努力呼吸生活里的真实空气闲逛在半静态下的午后圆明园', '2022-11-25 21:10:47')
(1469, '圆明园', '瑾秋视频', '2022-11-22 11:12', '初冬圆明园秋意浓~<br><br>', '2022-11-25 21:10:47')
(1470, '圆明园', '白雪皑皑银装素裹分外妖娆', '2022-11-22 12:29', '黑天鹅脖子上好像有个勒痕', '2022-11-25 21:10:47')

In [2]:
# # 选取前十个调试
# data_10 = data[:10]
# 全部数据
data_10 = data
import pandas as pd
# list_data = list(data_10)
def tuple_to_list(t1):
    return list(t1)
list_data = list(map(tuple_to_list,data_10))
#list_data

In [3]:
def split_data(list1):
    string1 = str(list1)
    list2 = string1.split(',')
    return list2
    
data_list_all = list(map(split_data,list_data))
#data_list_all

In [5]:
#### - comment_id: 0
#### - scence_name:1
#### - user_name:2
#### - comment_time:3
#### - comment_detail:4
#### - crawl_time:-1
# 将list换分为新list
list_comment_id = []
list_scence_name = []
list_user_name = []
list_comment_time = []
list_comment_detail = []
list_crawl_time = []

for list1 in data_list_all:
    string0 = str(list1[0]).replace('[','')
    string0 = int(string0)
    # 清洗comment_id数据,并转换为整数类型
    
    string1 = str(list1[1]).replace('\'','')
    string1 = string1.strip()
    # 清洗scence_name数据
    
    string2 = str(list1[2]).replace('\'','')
    string2 = string2.strip()
    # 清洗user_name数据   
    
    string3 = str(list1[3]).replace('\'','')
    string3 = string3.strip()
    # 清洗comment_time数据       
    
    string4 = str(list1[4]).replace('\'','')
    string4= string4.replace('<br>',' ')
    string4 = string4.strip()
    # 清洗comment_detail数据                                
    
    string_1 = str(list1[-1]).replace('\'','')
    string_1 = string_1.replace(']',' ')
    # 清洗crawl_time数据                                
        
    
    
    list_comment_id.append(string0) 
    list_scence_name.append(string1) 
    list_user_name.append(string2) 
    list_comment_time.append(string3)
    list_comment_detail.append(string4) 
    list_crawl_time.append(string_1) 
# 将数据转换为dataframework类型
# 构建字典
dic_new = {'comment_id':list_comment_id,
           'scence_name':list_scence_name,
           'user_name':list_user_name,
           'comment_time':list_comment_time,
           'comment_detail':list_comment_detail,
           'crawl_time':list_crawl_time}
data_new = pd.DataFrame(dic_new)
data_new

,comment_id,scence_name,user_name,comment_time,comment_detail,crawl_time
0,1451,圆明园,小桃枝枝,2022-11-25 17:50,明天就要降温了今天风好大,2022-11-25 21:10:47
1,1452,圆明园,繁星-满空,2022-11-25 19:29,这样能封一辈子吗病毒没死几个人防疫倒是快把人折磨死了,2022-11-25 21:10:47
2,1453,圆明园,Ronnie-Osullivan,2022-11-25 11:11,圆明园被烧十二年后长春园西洋楼花园门残影摄于公元1873同治十二年,2022-11-25 21:10:47
3,1454,圆明园,白雪皑皑银装素裹分外妖娆,2022-11-25 14:55,分享图片,2022-11-25 21:10:47
4,1455,圆明园,在学术边缘挣扎,2022-11-25 13:04,吃完饭坐上坐骑真舒服呀,2022-11-25 21:10:47
...,...,...,...,...,...,...
259062,267798,湖南省株洲市炎帝陵景区,青春败给了生活,2020-10-03 13:13,不要随便掏心掏肺，保留一部分神秘。 那是你在困境中，唯一能自救的东西。 —— 张皓宸,2022-11-28 13:42:06
259063,267799,湖南省株洲市炎帝陵景区,Mars-段雄伟,2019-10-05 19:23,一对情侣谈恋爱，总有一个强势的，一个随和的。一个厉害的，一个温顺的。一个勤快的，一个懒惰的。...,2022-11-28 13:42:06
259064,267800,湖南省株洲市炎帝陵景区,想做一条勇敢的咸鱼,2019-07-24 17:26,,2022-11-28 13:42:06
259065,267801,湖南省株洲市炎帝陵景区,制造精彩,2019-10-24 18:12,别有洞天,2022-11-28 13:42:06
259066,267802,湖南省株洲市炎帝陵景区,pandaweily,2019-08-16 13:18,分享图片,2022-11-28 13:42:06

In [5]:
data_new['count_1'] = 1
data_commentday = data_new.groupby(['scence_name']).agg({'count_1':'sum'})
data_commentday.to_csv('E:\\论文\\第二篇论文\\景点包含的微博数目.csv',encoding = 'utf-8-sig')

# 原始数据一共14,4480条数据,文字为0的数据有1,3764条,文字数目大于0小于200的文本数为13,0715
# 大于200的数据有1713条

In [6]:
# 计算大于200的评论数目
def count_chinese_words(string1):
    return len(string1)
list_comment_len = data_new['comment_detail'].apply(count_chinese_words)
data_new['comment_len'] = list_comment_len
data_new_less_200 = data_new[(data_new['comment_len']<200) & (data_new['comment_len']>0)]
new_list_comment_detail = data_new_less_200['comment_detail']
data_new_less_200

,comment_id,scence_name,user_name,comment_time,comment_detail,crawl_time,comment_len
0,1451,圆明园,小桃枝枝,2022-11-25 17:50,明天就要降温了今天风好大,2022-11-25 21:10:47,12
1,1452,圆明园,繁星-满空,2022-11-25 19:29,这样能封一辈子吗病毒没死几个人防疫倒是快把人折磨死了,2022-11-25 21:10:47,26
2,1453,圆明园,Ronnie-Osullivan,2022-11-25 11:11,圆明园被烧十二年后长春园西洋楼花园门残影摄于公元1873同治十二年,2022-11-25 21:10:47,33
3,1454,圆明园,白雪皑皑银装素裹分外妖娆,2022-11-25 14:55,分享图片,2022-11-25 21:10:47,4
4,1455,圆明园,在学术边缘挣扎,2022-11-25 13:04,吃完饭坐上坐骑真舒服呀,2022-11-25 21:10:47,11
...,...,...,...,...,...,...,...
259061,267797,湖南省株洲市炎帝陵景区,spring19880818,2019-03-01 13:34,公公出来咯,2022-11-28 13:42:06,5
259062,267798,湖南省株洲市炎帝陵景区,青春败给了生活,2020-10-03 13:13,不要随便掏心掏肺，保留一部分神秘。 那是你在困境中，唯一能自救的东西。 —— 张皓宸,2022-11-28 13:42:06,43
259063,267799,湖南省株洲市炎帝陵景区,Mars-段雄伟,2019-10-05 19:23,一对情侣谈恋爱，总有一个强势的，一个随和的。一个厉害的，一个温顺的。一个勤快的，一个懒惰的。...,2022-11-28 13:42:06,182
259065,267801,湖南省株洲市炎帝陵景区,制造精彩,2019-10-24 18:12,别有洞天,2022-11-28 13:42:06,4
259066,267802,湖南省株洲市炎帝陵景区,pandaweily,2019-08-16 13:18,分享图片,2022-11-28 13:42:06,4

In [7]:
data_new_more_200 = data_new[(data_new['comment_len']>200)]
data_new_more_200

,comment_id,scence_name,user_name,comment_time,comment_detail,crawl_time,comment_len
184,1635,圆明园,是我啊199408,2022-11-17 16:48,写论文前最后的挣扎十块钱的快乐 真的好喜欢一个人逛公园的感觉见到了红嘴大雁和黑嘴大雁入冬了只...,2022-11-25 21:12:00,218
211,1662,圆明园,古今画藏,2022-11-14 22:25,吴昌硕花卉册页欣赏 吴昌硕绘画的题材以花卉为主亦偶作山水前期得到任颐指点后又参用赵之谦画法并...,2022-11-25 21:12:00,287
296,1747,圆明园,chengyuweiii,2022-11-13 09:10,下车后刚进园子没走一会儿就想调头回去空气冷还夹着风穿少了好在太阳没下山一路走着看到有阳光的地...,2022-11-25 21:12:28,223
492,1943,圆明园,A王皮皮阿,2022-11-06 15:55,圆明园京东第一届试吃节 又到了一年一度拍银杏最美的季节了 今天跟朋友约着一起来圆明园的银杏...,2022-11-25 21:13:50,224
656,2107,圆明园,彩虹帮二当家,2022-11-01 21:15,2022年10月31日圆明园赏秋归来银杏叶已经90%变金黄啦快冲吧经过了昨天的大风地面也积起...,2022-11-25 21:15:13,230
...,...,...,...,...,...,...,...
258189,266925,昌吉回族自治州阜康市天山天池风景名胜区,Cherry_tingt,2022-07-10 00:32,酒店楼下就是客车站还挺方便 景区车开的好晚11点还堵车 但还不错晚上七点半才返回 天山天池啊...,2022-11-28 13:18:03,214
258280,267016,昌吉回族自治州阜康市天山天池风景名胜区,大6克,2022-07-07 21:21,游天山天池，聆听西王母传说 ；天山天池，有“天山明珠”之称，古称“瑶池”，位于天山山脉东部的...,2022-11-28 13:19:15,309
258950,267686,湖南省株洲市炎帝陵景区,G黄智雄,2020-09-29 08:43,【国家每三年一轮的三皇（黄帝、炎帝、舜帝）大祭，有两个在湖南（炎陵的炎帝、永州的舜帝）。陕西...,2022-11-28 13:41:22,412
258996,267732,湖南省株洲市炎帝陵景区,洪山竹海2022,2020-10-02 16:19,第一次来炎帝陵拜祭 炎帝陵是中华民族始祖炎帝神农氏的安息地。炎帝陵自宋乾德五年（967年）...,2022-11-28 13:41:50,212
259007,267743,湖南省株洲市炎帝陵景区,Missummer1985,2021-10-02 16:39,2021.09.24，湖南-株洲市（湘B）-炎陵县-炎帝陵。突然想到了两点：第一，去黄帝陵的...,2022-11-28 13:41:50,336

In [7]:
# 小于15字的数据一共有9,3175条数据，大于200字的数据一共有1,713条

In [8]:
# 这里建议先把所有数据都通过腾讯NLP跑一遍哦

In [9]:
# 师父的意思是，大于200字的也要做情感分析，我们可以先做出200字以内的为一个data_new_less_200
# 大于200字的为data_new_more_200

In [10]:
144479-130715

13764

In [11]:
# import json
# from tencentcloud.common import credential
# from tencentcloud.common.profile.client_profile import ClientProfile
# from tencentcloud.common.profile.http_profile import HttpProfile
# from tencentcloud.common.exception.tencent_cloud_sdk_exception import TencentCloudSDKException
# from tencentcloud.nlp.v20190408 import nlp_client, models
# list_median_sentiment = []
# try:
#     # 实例化一个认证对象，入参需要传入腾讯云账户secretId，secretKey,此处还需注意密钥对的保密
#     # 密钥可前往https://console.cloud.tencent.com/cam/capi网站进行获取
#     cred = credential.Credential("AKIDqVxB8oDMHwlLm6Bk23oCZovpVw71BBzX", "MSItEJAnBPO8d3GEwPedOu99vSEk14qM")

# # SecretId: AKIDqVxB8oDMHwlLm6Bk23oCZovpVw71BBzX
# # SecretKey: MSItEJAnBPO8d3GEwPedOu99vSEk14qM    
#     for text1 in new_list_comment_detail:
#     # 实例化一个http选项，可选的，没有特殊需求可以跳过
#         httpProfile = HttpProfile()
#         httpProfile.endpoint = "nlp.tencentcloudapi.com"

#     # 实例化一个client选项，可选的，没有特殊需求可以跳过
#         clientProfile = ClientProfile()
#         clientProfile.httpProfile = httpProfile
#     # 实例化要请求产品的client对象,clientProfile是可选的
#         client = nlp_client.NlpClient(cred, "ap-guangzhou", clientProfile)
    
    
        

#     # 实例化一个请求对象,每个接口都会对应一个request对象
#         req = models.SentimentAnalysisRequest()
#         params = {
#          "Text": text1,
#          "Mode": "3class"
#     }
#         req.from_json_string(json.dumps(params))

#     # 返回的resp是一个SentimentAnalysisResponse的实例，与请求对象对应
#         resp = client.SentimentAnalysis(req)
#         list_median_sentiment.append(resp.to_json_string())
#     # 输出json格式的字符串回包
#         print(resp.to_json_string())
# except TencentCloudSDKException as err:
#     print(err)

# print('all words less than 200 in compete!')

In [9]:
import math
# 针对大于200字的文本，我们可以将文本分割，每个文本200个字即可
# # 选取前10个评论来测试
# data_new_more_200_1 = data_new_more_200[:9]

# 选取全部评论来测试
data_new_more_200_1 = data_new_more_200

new2_data_over200 = []

list_texts_all = []
list_data_new_more200 = data_new_more_200_1['comment_detail']
for text in list_data_new_more200:
#     print(text)
#     print('\n')

    list_context_200 = []
    pages = math.ceil(len(text)/200)
    for num in range(pages):
        list_context_200.append(text[200*(num):200*(num+1)])
        list_texts_all.append(text[200*(num):200*(num+1)])
    new2_data_over200.append(list_context_200)
print(len(new2_data_over200))
print(len(list_texts_all))
# new2_data_over200 list1中套了list_texts,每个list_texts中为分段的评论

3076
7967

In [10]:
len(new2_data_over200)

3076

In [11]:
# list_num为id重复的次数
list_comments = []
def len_list(list1):
    a1 = len(list1)
    return a1
list_num = list(map(len_list,new2_data_over200))
len(list_num)

3076

In [12]:
list_id = list(data_new_more_200_1['comment_id'])

In [13]:
adjust_id_list = []
for num1 in range(len(list_num)):
   for i in range(list_num[num1]):
        adjust_id_list.append(list_id[num1])
len(adjust_id_list)

7967

In [15]:
data_adjust = {'comment_id': adjust_id_list,'comment_detail':list_texts_all}
data_adjust_more_than200 = pd.DataFrame(data = data_adjust)
list_more200_101 = data_adjust_more_than200['comment_detail']
data_adjust_more_than200

      comment_id                                     comment_detail
0           1635  写论文前最后的挣扎十块钱的快乐 真的好喜欢一个人逛公园的感觉见到了红嘴大雁和黑嘴大雁入冬了只...
1           1635                                 好了手机没电了该回家喽又是美好的一天
2           1662  吴昌硕花卉册页欣赏 吴昌硕绘画的题材以花卉为主亦偶作山水前期得到任颐指点后又参用赵之谦画法并...
3           1662  白喜取之字和女字格局或作对角斜势用色上似赵之谦喜用浓丽对比的颜色尤善用西洋红色泽浓艳吴昌硕因...
4           1747  下车后刚进园子没走一会儿就想调头回去空气冷还夹着风穿少了好在太阳没下山一路走着看到有阳光的地...
...          ...                                                ...
7962      267686                                       。 灵其鉴之，伏惟尚飨。
7963      267732  第一次来炎帝陵拜祭  炎帝陵是中华民族始祖炎帝神农氏的安息地。炎帝陵自宋乾德五年（967年）...
7964      267732                                       山、山西高平、河南柘城。
7965      267743  2021.09.24，湖南-株洲市（湘B）-炎陵县-炎帝陵。突然想到了两点：第一，去黄帝陵的...
7966      267743  耀邦同时一道来过这里，景区里有这个珍贵的老照片。每年都有很多海外华人回来祭祖！ 阪泉之战：黄...

[7967 rows x 2 columns]

In [35]:
# for i in list_more200_101:
#     print(len(i))

In [36]:
#计算
import json
from tencentcloud.common import credential
from tencentcloud.common.profile.client_profile import ClientProfile
from tencentcloud.common.profile.http_profile import HttpProfile
from tencentcloud.common.exception.tencent_cloud_sdk_exception import TencentCloudSDKException
from tencentcloud.nlp.v20190408 import nlp_client, models
list_median_sentiment = []
try:
    # 实例化一个认证对象，入参需要传入腾讯云账户secretId，secretKey,此处还需注意密钥对的保密
    # 密钥可前往https://console.cloud.tencent.com/cam/capi网站进行获取
    cred = credential.Credential("AKIDqVxB8oDMHwlLm6Bk23oCZovpVw71BBzX", "MSItEJAnBPO8d3GEwPedOu99vSEk14qM")

# SecretId: AKIDqVxB8oDMHwlLm6Bk23oCZovpVw71BBzX
# SecretKey: MSItEJAnBPO8d3GEwPedOu99vSEk14qM    
    for text1 in list_texts_all:
    # 实例化一个http选项，可选的，没有特殊需求可以跳过
        httpProfile = HttpProfile()
        httpProfile.endpoint = "nlp.tencentcloudapi.com"

    # 实例化一个client选项，可选的，没有特殊需求可以跳过
        clientProfile = ClientProfile()
        clientProfile.httpProfile = httpProfile
    # 实例化要请求产品的client对象,clientProfile是可选的
        client = nlp_client.NlpClient(cred, "ap-guangzhou", clientProfile)
    
    
        

    # 实例化一个请求对象,每个接口都会对应一个request对象
        req = models.SentimentAnalysisRequest()
        params = {
         "Text": text1,
         "Mode": "3class"
    }
        req.from_json_string(json.dumps(params))

    # 返回的resp是一个SentimentAnalysisResponse的实例，与请求对象对应
        resp = client.SentimentAnalysis(req)
        list_median_sentiment.append(resp.to_json_string())
    # 输出json格式的字符串回包
        print(resp.to_json_string())
except TencentCloudSDKException as err:
    print(err)

print('all words MORE than 200 in compete!')

{"Positive": 0.69381505, "Neutral": 0.18222061, "Negative": 0.12399434, "Sentiment": "positive", "RequestId": "606b9feb-2ae4-44ea-94d4-9a27b6656434"}
{"Positive": 0.18092413, "Neutral": 0.43365476, "Negative": 0.38545111, "Sentiment": "neutral", "RequestId": "bf1a9ee7-c2e0-4679-b21f-a37e966be776"}
{"Positive": 0.63316035, "Neutral": 0.26808229, "Negative": 0.0987874, "Sentiment": "positive", "RequestId": "1e1a1778-b55a-4aa2-8d48-b39831ce9e56"}
{"Positive": 0.69601762, "Neutral": 0.27748361, "Negative": 0.02652871, "Sentiment": "positive", "RequestId": "0e9ae5b6-a8bb-48fb-b3ed-a9591298c457"}
{"Positive": 0.40448114, "Neutral": 0.39399686, "Negative": 0.20155199, "Sentiment": "positive", "RequestId": "3db1a292-e01a-46f2-b19d-8c8b9ea6a623"}
{"Positive": 0.18410939, "Neutral": 0.14502566, "Negative": 0.67089498, "Sentiment": "negative", "RequestId": "94979e6a-4abe-41ba-a74d-88a89f6b31e4"}
{"Positive": 0.95270783, "Neutral": 0.03003169, "Negative": 0.01729055, "Sentiment": "positive", "RequestId": "18a06f36-63c6-427f-8d6f-635dea89d790"}
{"Positive": 0.9865787, "Neutral": 0.0006286, "Negative": 0.01282272, "Sentiment": "positive", "RequestId": "044f93a6-6411-47bb-a0d3-a1e7a5dd508f"}
{"Positive": 0.56036025, "Neutral": 0.38025054, "Negative": 0.05941921, "Sentiment": "positive", "RequestId": "ca96c0be-4482-4846-993b-bf82cb3c6de0"}
{"Positive": 0.51420647, "Neutral": 0.44394606, "Negative": 0.04187745, "Sentiment": "positive", "RequestId": "d68a7c12-1711-4665-9542-de7ce6f1345c"}
{"Positive": 0.07009446, "Neutral": 0.29435843, "Negative": 0.63557714, "Sentiment": "negative", "RequestId": "e01c545b-100e-40c6-ad2a-e0598a6acbad"}
{"Positive": 0.41669068, "Neutral": 0.48334691, "Negative": 0.09999234, "Sentiment": "neutral", "RequestId": "920ae18f-2e31-4716-9301-e54c55419ec3"}
{"Positive": 0.07215971, "Neutral": 0.39590994, "Negative": 0.53196037, "Sentiment": "negative", "RequestId": "83f82cb7-82ed-4da5-859c-4963cdaa1526"}
{"Positive": 0.21018261, "Neutral": 0.38577288, "Negative": 0.40407458, "Sentiment": "negative", "RequestId": "24680367-3010-488e-a5ce-76d5919a61e5"}
{"Positive": 0.48113355, "Neutral": 0.218371, "Negative": 0.30052549, "Sentiment": "positive", "RequestId": "aa2f28a1-43cc-4a36-8cc7-03172e8a65bf"}
{"Positive": 1.006e-05, "Neutral": 1.0000056, "Negative": 1.431e-05, "Sentiment": "neutral", "RequestId": "cf5926b0-d8e7-4e88-a034-f2ca4683955a"}
{"Positive": 0.40889248, "Neutral": 0.38127565, "Negative": 0.20986189, "Sentiment": "positive", "RequestId": "5f5a9b31-a117-4ec8-933e-6e8c1c99bd3b"}
{"Positive": 0.08309723, "Neutral": 0.50822687, "Negative": 0.40870595, "Sentiment": "neutral", "RequestId": "194a02de-fde7-4e83-ba9e-6fbe5a4f54b5"}
{"Positive": 0.04926883, "Neutral": 0.59542459, "Negative": 0.35533664, "Sentiment": "neutral", "RequestId": "a1682ed4-62d2-4c7f-8970-56dda7261f6a"}
{"Positive": 0.30122006, "Neutral": 0.39320368, "Negative": 0.30560625, "Sentiment": "neutral", "RequestId": "1067f97f-31c0-4350-bb2e-f4f99140ca24"}
{"Positive": 0.8539862, "Neutral": 0.06437095, "Negative": 0.08167284, "Sentiment": "positive", "RequestId": "549188d9-bb5d-4413-b542-2b94779c3a1e"}
{"Positive": 0.54640418, "Neutral": 0.44065571, "Negative": 0.01297007, "Sentiment": "positive", "RequestId": "b4859abb-70c2-4949-8ca9-d1f4873af219"}
{"Positive": 0.94985527, "Neutral": 0.01129565, "Negative": 0.0388791, "Sentiment": "positive", "RequestId": "1f52a883-8dcb-4e95-bf89-3c4989e9a770"}
{"Positive": 0.36929393, "Neutral": 0.42561537, "Negative": 0.20512071, "Sentiment": "neutral", "RequestId": "a6d0ae45-3085-43d0-a58c-ebb1047ca9a2"}
{"Positive": 0.51351136, "Neutral": 0.22694251, "Negative": 0.25957617, "Sentiment": "positive", "RequestId": "52fddbdd-2aa7-4b8b-b2c7-38e0920c8eea"}
{"Positive": 0.42760587, "Neutral": 0.49153432, "Negative": 0.08088982, "Sentiment": "neutral", "RequestId": "09767fe2-f664-4238-8172-5ced106dd8f7"}
{"Positive": 0.43288741, "Neutral": 0.36755112, "Negative": 0.1995915, "Sentiment": "positive", "RequestId": "73cd33f8-c875-43b1-a5c5-f6035d8e35dd"}
{"Positive": 0.18750866, "Neutral": 0.53535122, "Negative": 0.27717018, "Sentiment": "neutral", "RequestId": "b54d5356-b1e2-4812-86cf-b38f692a12ad"}
{"Positive": 0.29556927, "Neutral": 0.42508137, "Negative": 0.27937934, "Sentiment": "neutral", "RequestId": "a4c8772a-860e-4a17-b506-cce522b85b6c"}
{"Positive": 0.08102331, "Neutral": 0.52144736, "Negative": 0.39755931, "Sentiment": "neutral", "RequestId": "242d7763-cb61-4455-9222-266e503ee908"}
{"Positive": 0.23357403, "Neutral": 0.36932302, "Negative": 0.39713287, "Sentiment": "negative", "RequestId": "96cb4469-5b1c-4145-9aac-3c749550cc6f"}
{"Positive": 0.04159749, "Neutral": 0.12856971, "Negative": 0.82986283, "Sentiment": "negative", "RequestId": "b428f36c-9107-4673-8f60-36e5692d2e81"}
{"Positive": 0.21994837, "Neutral": 0.25973436, "Negative": 0.52034724, "Sentiment": "negative", "RequestId": "b4b0e115-79b9-41aa-9468-ee85abfbc8c9"}
{"Positive": 0.34481317, "Neutral": 0.4279055, "Negative": 0.22731139, "Sentiment": "neutral", "RequestId": "6fc3ded0-448e-46cf-96eb-c3d81c9078a4"}
{"Positive": 0.56825906, "Neutral": 0.35776284, "Negative": 0.07400819, "Sentiment": "positive", "RequestId": "2318c2b1-cfbb-441e-9fd3-2118b52bf579"}
{"Positive": 0.19107491, "Neutral": 0.78425872, "Negative": 0.0246964, "Sentiment": "neutral", "RequestId": "fe1a9fcc-6994-4275-931b-31a88d79063b"}
{"Positive": 0.50553274, "Neutral": 0.27148473, "Negative": 0.22301254, "Sentiment": "positive", "RequestId": "65866200-a65b-4ff5-b09d-c3b42c5ff1d2"}
{"Positive": 0.94550359, "Neutral": 0.02240912, "Negative": 0.03211741, "Sentiment": "positive", "RequestId": "e54f9b33-f870-4daa-82a1-df059721b0b6"}
{"Positive": 0.38196886, "Neutral": 0.47649491, "Negative": 0.1415662, "Sentiment": "neutral", "RequestId": "7920788b-5793-4b0d-8e61-be295fe399e4"}
{"Positive": 0.10979348, "Neutral": 0.43402851, "Negative": 0.45620796, "Sentiment": "negative", "RequestId": "270ecc6a-2d24-4b30-b8c9-fa4a16451aa1"}
{"Positive": 0.29474759, "Neutral": 0.31533405, "Negative": 0.3899484, "Sentiment": "negative", "RequestId": "590a655b-7c16-4381-b340-99998dbadae8"}
{"Positive": 0.13773584, "Neutral": 0.17733419, "Negative": 0.68495995, "Sentiment": "negative", "RequestId": "ff256155-1dcc-4a67-9b1a-07dd73edc937"}
{"Positive": 0.58569968, "Neutral": 0.32908916, "Negative": 0.08524119, "Sentiment": "positive", "RequestId": "81c840b4-db19-452d-9c01-ea8bedaa1b57"}
{"Positive": 0.38821381, "Neutral": 0.30297843, "Negative": 0.30883774, "Sentiment": "positive", "RequestId": "e0b0b57c-1131-4e64-9693-e20269be54bb"}
{"Positive": 0.42076358, "Neutral": 0.25897345, "Negative": 0.32029301, "Sentiment": "positive", "RequestId": "a5b190b3-db18-4afd-8d74-58216047f631"}
{"Positive": 0.06827024, "Neutral": 0.53856814, "Negative": 0.3931917, "Sentiment": "neutral", "RequestId": "ed1fa6dc-8773-43d1-b94c-f238cb81b27c"}
{"Positive": 0.5095498, "Neutral": 0.0977558, "Negative": 0.39272445, "Sentiment": "positive", "RequestId": "4320022d-1e70-44d5-898c-5ca947a45812"}
{"Positive": 0.45468101, "Neutral": 0.40037909, "Negative": 0.14496991, "Sentiment": "positive", "RequestId": "aec6783e-98b7-4b2a-9532-19ece610e068"}
{"Positive": 0.60381013, "Neutral": 0.12032992, "Negative": 0.27588999, "Sentiment": "positive", "RequestId": "611d3e2d-8c14-4fc6-b211-7ac4f959ef60"}
{"Positive": 0.29225153, "Neutral": 0.41687322, "Negative": 0.29090524, "Sentiment": "neutral", "RequestId": "dc70988a-b467-4a80-8ddd-1581fd74d37c"}
{"Positive": 0.1370023, "Neutral": 0.57928634, "Negative": 0.28374135, "Sentiment": "neutral", "RequestId": "dc59276b-756d-4ce0-b267-2c6a6176a455"}
{"Positive": 0.34183308, "Neutral": 0.51934546, "Negative": 0.13885146, "Sentiment": "neutral", "RequestId": "713ea449-5429-4c2b-a873-01ba0c871790"}
{"Positive": 0.51002371, "Neutral": 0.40666994, "Negative": 0.08333633, "Sentiment": "positive", "RequestId": "dc514d28-cefe-4cc7-a319-452cd97f55f4"}
{"Positive": 0.24041766, "Neutral": 0.61217898, "Negative": 0.1474333, "Sentiment": "neutral", "RequestId": "4f9b8bb5-780e-4b8f-a2a2-4fb81d7be355"}
{"Positive": 0.20603757, "Neutral": 0.7867716, "Negative": 0.00722082, "Sentiment": "neutral", "RequestId": "2764904a-de70-4a3c-8e2c-87dcae5af06c"}
{"Positive": 0.06871971, "Neutral": 0.41295418, "Negative": 0.51835608, "Sentiment": "negative", "RequestId": "703cd039-f611-4212-bef6-115a83e79fce"}
{"Positive": 0.34775534, "Neutral": 0.33008191, "Negative": 0.3221927, "Sentiment": "positive", "RequestId": "c1db5769-2a09-44a7-a258-bc0003f32e90"}
{"Positive": 0.34880099, "Neutral": 0.52558804, "Negative": 0.12564102, "Sentiment": "neutral", "RequestId": "36a82f74-371d-448c-b1f8-0af6fd871724"}
{"Positive": 0.1847959, "Neutral": 0.60532635, "Negative": 0.20990773, "Sentiment": "neutral", "RequestId": "7f73a75e-583f-4405-9db6-1f5175067708"}
{"Positive": 0.34034625, "Neutral": 0.14769791, "Negative": 0.51198584, "Sentiment": "negative", "RequestId": "cf44f436-7262-4380-9eab-778e6aedc2aa"}
{"Positive": 0.86591822, "Neutral": 0.0527353, "Negative": 0.08137641, "Sentiment": "positive", "RequestId": "ae584415-3b27-49ae-9981-b76a5e68df35"}
{"Positive": 0.27136642, "Neutral": 0.27777982, "Negative": 0.45088369, "Sentiment": "negative", "RequestId": "4b8a5c0f-7c86-4fce-9f4e-52890cdf9dc0"}
{"Positive": 0.28627297, "Neutral": 0.420614, "Negative": 0.29314303, "Sentiment": "neutral", "RequestId": "05926772-0777-4f0a-a204-775079b932a8"}
{"Positive": 0.61508602, "Neutral": 0.2427796, "Negative": 0.14216438, "Sentiment": "positive", "RequestId": "20d2709c-c922-49de-a5a0-9efc97ec3373"}
{"Positive": 0.61124939, "Neutral": 0.23188317, "Negative": 0.15689744, "Sentiment": "positive", "RequestId": "d26387ab-de47-4081-b641-78cd0a0aee90"}
{"Positive": 0.65456277, "Neutral": 0.2802614, "Negative": 0.06520583, "Sentiment": "positive", "RequestId": "96a025f0-f080-4d2b-bc0f-dcf9616d6e7a"}
{"Positive": 0.11709202, "Neutral": 0.67659396, "Negative": 0.20634401, "Sentiment": "neutral", "RequestId": "ca0345b6-1597-4fcd-aec5-168cdfd3ef0e"}
{"Positive": 0.2017082, "Neutral": 0.57868773, "Negative": 0.21963412, "Sentiment": "neutral", "RequestId": "0c8ccd18-16f5-4d8e-bee4-96cefd4bd9ce"}
{"Positive": 0.22329359, "Neutral": 0.48468491, "Negative": 0.29205149, "Sentiment": "neutral", "RequestId": "65c485dc-5981-49d7-bf46-fdf1be085b08"}
{"Positive": 0.14317863, "Neutral": 0.71411085, "Negative": 0.14274049, "Sentiment": "neutral", "RequestId": "d2ac9e37-7cc2-43d5-aee6-2caa97254662"}
{"Positive": 0.43200561, "Neutral": 0.41815618, "Negative": 0.14986821, "Sentiment": "positive", "RequestId": "9d44cb26-2124-44f6-8994-8178dd22f767"}
{"Positive": 0.31717664, "Neutral": 0.41911435, "Negative": 0.26373905, "Sentiment": "neutral", "RequestId": "5a0b8302-b3dc-40d6-9bd2-5891a55f44b9"}
{"Positive": 0.56091821, "Neutral": 0.39203456, "Negative": 0.04707731, "Sentiment": "positive", "RequestId": "982aa90e-36de-43ca-8e82-9bf391dd0437"}
{"Positive": 0.72554511, "Neutral": 0.20509031, "Negative": 0.06939451, "Sentiment": "positive", "RequestId": "7505d0c5-006f-49c5-8c71-e52e6dce3941"}
{"Positive": 0.71442372, "Neutral": 0.20285578, "Negative": 0.0827505, "Sentiment": "positive", "RequestId": "ac04d88a-8487-4304-b339-8bcc9263a349"}
{"Positive": 0.23763445, "Neutral": 0.23088238, "Negative": 0.53151315, "Sentiment": "negative", "RequestId": "00ce0a4a-182d-4236-801f-681a3fd9d7ec"}
{"Positive": 0.32805756, "Neutral": 0.56421793, "Negative": 0.10775455, "Sentiment": "neutral", "RequestId": "b3c38e01-3213-4601-931b-b1701381e789"}
{"Positive": 0.576626, "Neutral": 0.11092604, "Negative": 0.31247795, "Sentiment": "positive", "RequestId": "2faa578b-d837-41a5-a6b6-93a3107c4c52"}
{"Positive": 0.34869754, "Neutral": 0.54619163, "Negative": 0.10514084, "Sentiment": "neutral", "RequestId": "bf8d3ded-2127-48f2-bbf9-da0007c81e7f"}
{"Positive": 0.9900955, "Neutral": 0.00838293, "Negative": 0.00155152, "Sentiment": "positive", "RequestId": "5a648cda-fbba-41bb-a7dd-7617e72e6666"}
{"Positive": 0.77435833, "Neutral": 0.14820281, "Negative": 0.07746897, "Sentiment": "positive", "RequestId": "3c220578-da18-4b27-b8ef-5f7087d3b78b"}
{"Positive": 0.93788373, "Neutral": 0.02561615, "Negative": 0.03653006, "Sentiment": "positive", "RequestId": "a0bb5d79-3746-4bc7-97fd-be0a0c8acc43"}
{"Positive": 0.62364107, "Neutral": 0.16889933, "Negative": 0.20748961, "Sentiment": "positive", "RequestId": "466427a9-28ca-4674-bcd0-d351731060ca"}
{"Positive": 0.28706113, "Neutral": 0.46395281, "Negative": 0.24901605, "Sentiment": "neutral", "RequestId": "22fa97ac-8ac4-4c2d-b01c-fdc913662229"}
{"Positive": 0.37342107, "Neutral": 0.56028336, "Negative": 0.06632552, "Sentiment": "neutral", "RequestId": "78481755-170d-4eba-8f27-e29447ecc64f"}
{"Positive": 0.08172978, "Neutral": 0.16422829, "Negative": 0.75407195, "Sentiment": "negative", "RequestId": "575998b8-0016-4883-b2d8-38184e4f86a7"}
{"Positive": 0.52814537, "Neutral": 0.34352916, "Negative": 0.12835549, "Sentiment": "positive", "RequestId": "362c9832-af63-40a1-9be7-f00d5e596eb3"}
{"Positive": 0.23166975, "Neutral": 0.10527152, "Negative": 0.66308874, "Sentiment": "negative", "RequestId": "04ef0b56-653b-4d7f-bc7b-0d6bb199dd7a"}
{"Positive": 0.58524883, "Neutral": 0.3735297, "Negative": 0.04125148, "Sentiment": "positive", "RequestId": "62490168-f962-43fa-b465-1ea583c281f7"}
{"Positive": 0.45940417, "Neutral": 0.39663985, "Negative": 0.14398597, "Sentiment": "positive", "RequestId": "c74ffc3b-3d65-4f3e-b377-c5e228efd684"}
{"Positive": 0.51181006, "Neutral": 0.28003496, "Negative": 0.208185, "Sentiment": "positive", "RequestId": "d418bf79-5794-4729-bb5b-7b6f755a5acb"}
{"Positive": 0.53765422, "Neutral": 0.36389992, "Negative": 0.09847591, "Sentiment": "positive", "RequestId": "843c606f-bb01-4476-a3c5-ca7bd0257f89"}
{"Positive": 0.76231235, "Neutral": 0.11037683, "Negative": 0.12734093, "Sentiment": "positive", "RequestId": "ad51e90a-c607-4125-9096-9784f530f45f"}
{"Positive": 0.06581687, "Neutral": 0.41569698, "Negative": 0.51851618, "Sentiment": "negative", "RequestId": "0d73a2c0-a9b2-4159-82a0-d99e9263e001"}
{"Positive": 0.01169665, "Neutral": 0.13606815, "Negative": 0.85226518, "Sentiment": "negative", "RequestId": "90222de8-97fd-41a0-bbd3-94503f29c8bc"}
{"Positive": 0.40261814, "Neutral": 0.50994903, "Negative": 0.08746286, "Sentiment": "neutral", "RequestId": "da9e3603-d440-46f4-bd8a-efcc2ca6d9d8"}
{"Positive": 0.34710425, "Neutral": 0.50100917, "Negative": 0.15191659, "Sentiment": "neutral", "RequestId": "9ff86a39-8872-499b-979a-ae4bddc41ed9"}
{"Positive": 0.30676511, "Neutral": 0.34452763, "Negative": 0.34873724, "Sentiment": "negative", "RequestId": "1b51b311-073c-4783-91a9-ee5c650aee94"}
{"Positive": 0.21395646, "Neutral": 0.32794639, "Negative": 0.45812708, "Sentiment": "negative", "RequestId": "1b73a4b6-6625-4dde-ae5f-968b65690184"}
{"Positive": 0.30676511, "Neutral": 0.34452763, "Negative": 0.34873724, "Sentiment": "negative", "RequestId": "1108fdd3-a069-4fa0-b516-0817a344c1cc"}
{"Positive": 0.21395646, "Neutral": 0.32794639, "Negative": 0.45812708, "Sentiment": "negative", "RequestId": "27a812b9-398a-4368-90e7-6be05411057a"}
{"Positive": 0.15781206, "Neutral": 0.71092647, "Negative": 0.13129151, "Sentiment": "neutral", "RequestId": "c46db4e8-4967-42c2-85ce-1bc57dc0bae4"}
{"Positive": 0.09105025, "Neutral": 0.26665315, "Negative": 0.64232659, "Sentiment": "negative", "RequestId": "2a1460a7-7286-4a1d-91b1-66c6b8fe9c6e"}
{"Positive": 0.53185725, "Neutral": 0.38081506, "Negative": 0.08735769, "Sentiment": "positive", "RequestId": "e547d435-92c2-4fcc-bf14-648cfc5b292e"}
{"Positive": 0.2741634, "Neutral": 0.7193855, "Negative": 0.00648112, "Sentiment": "neutral", "RequestId": "1a5aeaa8-8864-4432-825e-acade13c00dc"}
{"Positive": 0.28842929, "Neutral": 0.43367171, "Negative": 0.27792898, "Sentiment": "neutral", "RequestId": "a59bf117-6a1a-4df6-a3fb-96e9a548d9cb"}
{"Positive": 0.37539151, "Neutral": 0.54242808, "Negative": 0.08221038, "Sentiment": "neutral", "RequestId": "07211c9d-40bc-4e4f-b713-64556adc6d09"}
{"Positive": 0.47288609, "Neutral": 0.3041195, "Negative": 0.22302443, "Sentiment": "positive", "RequestId": "a1bee723-8267-4e5a-949a-5355a43f4109"}
{"Positive": 0.30088636, "Neutral": 0.41690052, "Negative": 0.28224313, "Sentiment": "neutral", "RequestId": "6315c340-8adf-4a44-8840-e2998c436aa8"}
{"Positive": 0.24748614, "Neutral": 0.61797094, "Negative": 0.13457301, "Sentiment": "neutral", "RequestId": "7ab0a550-1966-415a-a002-205574f072f3"}
{"Positive": 0.50129199, "Neutral": 0.33387366, "Negative": 0.16486433, "Sentiment": "positive", "RequestId": "59e60c19-06eb-40f2-9215-3d23d8b9959c"}
{"Positive": 0.55331182, "Neutral": 0.24495457, "Negative": 0.20176363, "Sentiment": "positive", "RequestId": "0ddd57fe-7580-48ec-b94f-4a8bcc445a0e"}
{"Positive": 0.70704514, "Neutral": 0.24670091, "Negative": 0.046284, "Sentiment": "positive", "RequestId": "eb80f897-a5f8-4df2-8ab1-a0c9072d934d"}
{"Positive": 0.28976411, "Neutral": 0.61678886, "Negative": 0.09347702, "Sentiment": "neutral", "RequestId": "849872b5-9ee0-499f-8043-b480345f64e2"}
{"Positive": 0.4636789, "Neutral": 0.35253659, "Negative": 0.1838145, "Sentiment": "positive", "RequestId": "42bfbf66-950d-4b91-bc7d-650c806c785c"}
{"Positive": 0.44592816, "Neutral": 0.46105415, "Negative": 0.09304769, "Sentiment": "neutral", "RequestId": "70c9f8e9-1e67-497d-9e1a-c57cd2c1f82b"}
{"Positive": 0.52798367, "Neutral": 0.37840259, "Negative": 0.0936438, "Sentiment": "positive", "RequestId": "656cc427-978f-44fe-833a-274e82895839"}
{"Positive": 0.3650195, "Neutral": 0.50612909, "Negative": 0.12888142, "Sentiment": "neutral", "RequestId": "5d5c8c4c-54e5-418a-9931-3a2da30650e6"}
{"Positive": 0.22239238, "Neutral": 0.51238495, "Negative": 0.26525265, "Sentiment": "neutral", "RequestId": "c2538d6f-51d0-4d59-b01a-c66f0b4b18ee"}
{"Positive": 0.55183178, "Neutral": 0.37709174, "Negative": 0.07110649, "Sentiment": "positive", "RequestId": "4e7c21a1-ce54-47a2-8171-2450c1f4a8ac"}
{"Positive": 0.49229106, "Neutral": 0.23860922, "Negative": 0.26912966, "Sentiment": "positive", "RequestId": "aacb613f-edb3-441e-a4e4-cca9c725151f"}
{"Positive": 0.62502885, "Neutral": 0.07272068, "Negative": 0.30228046, "Sentiment": "positive", "RequestId": "a440f2b0-be8a-487f-b003-6505f335544e"}
{"Positive": 0.42981532, "Neutral": 0.30566278, "Negative": 0.26455182, "Sentiment": "positive", "RequestId": "ed099235-7021-4e69-bbb0-66c2bb21162d"}
{"Positive": 0.47679353, "Neutral": 0.5077045, "Negative": 0.01553198, "Sentiment": "neutral", "RequestId": "6c59b362-255a-4111-a30b-f6f91af82546"}
{"Positive": 0.49613592, "Neutral": 0.25186762, "Negative": 0.25202656, "Sentiment": "positive", "RequestId": "f0600b5a-7815-4a0f-a798-2732be0b6c96"}
{"Positive": 0.76212549, "Neutral": 0.08544591, "Negative": 0.15245865, "Sentiment": "positive", "RequestId": "7a1a5138-4cd7-4552-8e8a-8494574dddf1"}
{"Positive": 0.58177859, "Neutral": 0.26299557, "Negative": 0.15525594, "Sentiment": "positive", "RequestId": "bd6514ec-4636-4abd-843f-7d833336823b"}
{"Positive": 0.66133773, "Neutral": 0.27278039, "Negative": 0.06591186, "Sentiment": "positive", "RequestId": "0567d992-eabc-44bb-8d90-9791e9c8db8d"}
{"Positive": 0.5525018, "Neutral": 0.28241628, "Negative": 0.16511185, "Sentiment": "positive", "RequestId": "33b4a039-de78-4f22-a58a-8cc948793cd6"}
{"Positive": 0.50648326, "Neutral": 0.35906094, "Negative": 0.13448581, "Sentiment": "positive", "RequestId": "de08defb-967f-4933-a9dd-5ac71599448b"}
{"Positive": 0.35644555, "Neutral": 0.45653027, "Negative": 0.18705422, "Sentiment": "neutral", "RequestId": "ddb70c7d-272d-4289-b3d6-a4c6c691c7d7"}
{"Positive": 0.59942389, "Neutral": 0.1520294, "Negative": 0.24857666, "Sentiment": "positive", "RequestId": "397f65d4-2387-47f7-9a98-824f4b8e26b7"}
{"Positive": 0.52058822, "Neutral": 0.19028887, "Negative": 0.28915289, "Sentiment": "positive", "RequestId": "0ee0b6da-96bf-461a-b5d6-cfb3437b6a32"}

In [37]:
# 将list_median_sentimen进行拆分
# dic_list_median_sentiment = list_median_sentiment[1]
def string_dic(string1):
    string1 = string1.replace('{','')
    string1 = string1.replace('}','')
    string1 = string1.replace('"','')
    dic_item_median_sentiment = dict(x.split(":") for x in string1.split(","))
    return dic_item_median_sentiment
#

In [38]:
# string_dic(list_median_sentiment)
# list_median_sentiment1 = list(map(string_dic,list_median_sentiment))
# list_median_sentiment1
list_median_new = []

# {"Positive": 0.36061561, "Neutral": 0.53547966, "Negative": 0.10393469, "Sentiment": "neutral", "RequestId": "dbc96b0e-a81d-4b5b-89d6-f41483e567b7"}


list_median_Positive = []
list_median_Neutral = []
list_median_Negative = []
list_median_Sentiment = []
list_median_RequestId = []

for item1 in list_median_sentiment:
    list_values = []
    item_median = string_dic(item1)
    list_values = list(item_median.values())
    list_median_Positive.append(float(list_values[0])*100)
    list_median_Neutral.append(float(list_values[1])*100)
    list_median_Negative.append(float(list_values[2])*100)
    list_median_Sentiment.append(list_values[3])
    list_median_RequestId.append(list_values[4])
    
    # list_median_new.append(item_median)
print(len(list_median_Positive))
print(len(list_median_Neutral))
print(len(list_median_Negative))
print(len(list_median_Sentiment))
print(len(list_median_RequestId))

7967
7967
7967
7967
7967

In [39]:
# new_list_comment_detail = data_new['comment_detail']
# list_median_Positive = []
# list_median_Neutral = []
# list_median_Negative = []
# list_median_Sentiment = []
# list_median_RequestId = []

data_adjust_more_than200['Positive'] = list_median_Positive
data_adjust_more_than200['Neutral'] = list_median_Neutral
data_adjust_more_than200['Negative'] = list_median_Negative
data_adjust_more_than200['Sentiment'] = list_median_Sentiment
data_adjust_more_than200['RequestId'] = list_median_RequestId
data_adjust_more_than200

,comment_id,comment_detail,Positive,Neutral,Negative,Sentiment,RequestId
0,1635,写论文前最后的挣扎十块钱的快乐 真的好喜欢一个人逛公园的感觉见到了红嘴大雁和黑嘴大雁入冬了只...,69.381505,18.222061,12.399434,positive,606b9feb-2ae4-44ea-94d4-9a27b6656434
1,1635,好了手机没电了该回家喽又是美好的一天,18.092413,43.365476,38.545111,neutral,bf1a9ee7-c2e0-4679-b21f-a37e966be776
2,1662,吴昌硕花卉册页欣赏 吴昌硕绘画的题材以花卉为主亦偶作山水前期得到任颐指点后又参用赵之谦画法并...,63.316035,26.808229,9.878740,positive,1e1a1778-b55a-4aa2-8d48-b39831ce9e56
3,1662,白喜取之字和女字格局或作对角斜势用色上似赵之谦喜用浓丽对比的颜色尤善用西洋红色泽浓艳吴昌硕因...,69.601762,27.748361,2.652871,positive,0e9ae5b6-a8bb-48fb-b3ed-a9591298c457
4,1747,下车后刚进园子没走一会儿就想调头回去空气冷还夹着风穿少了好在太阳没下山一路走着看到有阳光的地...,40.448114,39.399686,20.155199,positive,3db1a292-e01a-46f2-b19d-8c8b9ea6a623
...,...,...,...,...,...,...,...
7962,267686,。 灵其鉴之，伏惟尚飨。,9.837313,29.142118,61.023575,negative,617fdcae-eab5-42a5-b8f2-7b50760dd9b6
7963,267732,第一次来炎帝陵拜祭 炎帝陵是中华民族始祖炎帝神农氏的安息地。炎帝陵自宋乾德五年（967年）...,14.625964,31.676888,53.700155,negative,d63399cf-e3e0-4377-b7cb-38b5f79787b1
7964,267732,山、山西高平、河南柘城。,8.492211,90.697861,0.812928,neutral,7d988885-eaf7-423c-bde0-c0eeb4ce9d49
7965,267743,2021.09.24，湖南-株洲市（湘B）-炎陵县-炎帝陵。突然想到了两点：第一，去黄帝陵的...,47.044381,39.617777,13.340843,positive,6967ff60-7667-4d5f-ba89-30a6d0f144d9
7966,267743,耀邦同时一道来过这里，景区里有这个珍贵的老照片。每年都有很多海外华人回来祭祖！ 阪泉之战：黄...,17.496772,71.221769,11.284463,neutral,f178f682-78a3-4487-9e11-a27f806a81d1

In [40]:
data_adjust_more_than200.to_csv('medianResult_commentLevel_more200.csv')

In [ ]:
data_new
# 属性有
# 	comment_id	scence_name	user_name	comment_time	comment_detail	crawl_time	comment_len

In [19]:
# 将data_adjust_more_than200于data_new左连接
import pandas as pd
data_ajust_merge = pd.merge(data_adjust_more_than200,data_new,on = ['comment_id'],how='left')
data_ajust_merge

,comment_id,comment_detail_x,scence_name,user_name,comment_time,comment_detail_y,crawl_time,comment_len
0,1635,写论文前最后的挣扎十块钱的快乐 真的好喜欢一个人逛公园的感觉见到了红嘴大雁和黑嘴大雁入冬了只...,圆明园,是我啊199408,2022-11-17 16:48,写论文前最后的挣扎十块钱的快乐 真的好喜欢一个人逛公园的感觉见到了红嘴大雁和黑嘴大雁入冬了只...,2022-11-25 21:12:00,218
1,1635,好了手机没电了该回家喽又是美好的一天,圆明园,是我啊199408,2022-11-17 16:48,写论文前最后的挣扎十块钱的快乐 真的好喜欢一个人逛公园的感觉见到了红嘴大雁和黑嘴大雁入冬了只...,2022-11-25 21:12:00,218
2,1662,吴昌硕花卉册页欣赏 吴昌硕绘画的题材以花卉为主亦偶作山水前期得到任颐指点后又参用赵之谦画法并...,圆明园,古今画藏,2022-11-14 22:25,吴昌硕花卉册页欣赏 吴昌硕绘画的题材以花卉为主亦偶作山水前期得到任颐指点后又参用赵之谦画法并...,2022-11-25 21:12:00,287
3,1662,白喜取之字和女字格局或作对角斜势用色上似赵之谦喜用浓丽对比的颜色尤善用西洋红色泽浓艳吴昌硕因...,圆明园,古今画藏,2022-11-14 22:25,吴昌硕花卉册页欣赏 吴昌硕绘画的题材以花卉为主亦偶作山水前期得到任颐指点后又参用赵之谦画法并...,2022-11-25 21:12:00,287
4,1747,下车后刚进园子没走一会儿就想调头回去空气冷还夹着风穿少了好在太阳没下山一路走着看到有阳光的地...,圆明园,chengyuweiii,2022-11-13 09:10,下车后刚进园子没走一会儿就想调头回去空气冷还夹着风穿少了好在太阳没下山一路走着看到有阳光的地...,2022-11-25 21:12:28,223
...,...,...,...,...,...,...,...,...
7962,267686,。 灵其鉴之，伏惟尚飨。,湖南省株洲市炎帝陵景区,G黄智雄,2020-09-29 08:43,【国家每三年一轮的三皇（黄帝、炎帝、舜帝）大祭，有两个在湖南（炎陵的炎帝、永州的舜帝）。陕西...,2022-11-28 13:41:22,412
7963,267732,第一次来炎帝陵拜祭 炎帝陵是中华民族始祖炎帝神农氏的安息地。炎帝陵自宋乾德五年（967年）...,湖南省株洲市炎帝陵景区,洪山竹海2022,2020-10-02 16:19,第一次来炎帝陵拜祭 炎帝陵是中华民族始祖炎帝神农氏的安息地。炎帝陵自宋乾德五年（967年）...,2022-11-28 13:41:50,212
7964,267732,山、山西高平、河南柘城。,湖南省株洲市炎帝陵景区,洪山竹海2022,2020-10-02 16:19,第一次来炎帝陵拜祭 炎帝陵是中华民族始祖炎帝神农氏的安息地。炎帝陵自宋乾德五年（967年）...,2022-11-28 13:41:50,212
7965,267743,2021.09.24，湖南-株洲市（湘B）-炎陵县-炎帝陵。突然想到了两点：第一，去黄帝陵的...,湖南省株洲市炎帝陵景区,Missummer1985,2021-10-02 16:39,2021.09.24，湖南-株洲市（湘B）-炎陵县-炎帝陵。突然想到了两点：第一，去黄帝陵的...,2022-11-28 13:41:50,336
7966,267743,耀邦同时一道来过这里，景区里有这个珍贵的老照片。每年都有很多海外华人回来祭祖！ 阪泉之战：黄...,湖南省株洲市炎帝陵景区,Missummer1985,2021-10-02 16:39,2021.09.24，湖南-株洲市（湘B）-炎陵县-炎帝陵。突然想到了两点：第一，去黄帝陵的...,2022-11-28 13:41:50,336

In [5]:
data_ajust_merge.to_csv('E:\\论文\\第二篇论文\\0227超过200的数据第二版.csv',encoding = 'utf-8-sig')

NameError: name 'data_ajust_merge' is not defined

In [178]:
# data_over_15 = data_less_200 + data_ajust_merge
data_over_15 = pd.concat([data_less_200,data_ajust_merge],axis=0)
data_over_15

,Unnamed: 0,comment_id,scence_name,user_name,comment_time,comment_detail,crawl_time,comment_len,Positive,Neutral,Negative,Sentiment,RequestId,comment_detail_x,comment_detail_y
0,1.0,1452,圆明园,繁星-满空,2022-11-25 19:29,这样能封一辈子吗病毒没死几个人防疫倒是快把人折磨死了,2022-11-25 21:10:47,26,2.416031,8.446255,89.140707,negative,27fd1a48-f9df-4cae-93bf-eccd6c093a40,NaN,NaN
1,2.0,1453,圆明园,Ronnie-Osullivan,2022-11-25 11:11,圆明园被烧十二年后长春园西洋楼花园门残影摄于公元1873同治十二年,2022-11-25 21:10:47,33,43.924150,54.498631,1.580220,neutral,ca020d0f-a8c8-4c35-a7d3-ec30bf8b2fbd,NaN,NaN
2,6.0,1457,圆明园,星儿_薇薇子,2022-11-24 17:48,在这个昏沉沉的天里只有它们才是无忧无虑吧,2022-11-25 21:10:47,20,12.629884,53.156751,34.216365,neutral,ac37db20-684a-4207-8401-ef36157ecc0a,NaN,NaN
3,14.0,1465,圆明园,想养缅因猫06,2022-11-23 16:03,每年冬天疫情必来一次圆明园真不希望以这种方式逛园子,2022-11-25 21:10:47,25,60.023665,17.173688,22.805646,positive,7b3b8200-4e66-475c-a2e6-08fba6ddea41,NaN,NaN
4,15.0,1466,圆明园,王小虎呦,2022-11-22 21:11,今年秋天好长景色好美唯一值得开心点的事情了,2022-11-25 21:10:47,21,99.599493,0.345477,0.058035,positive,c64da446-d670-47f8-bc52-3689e7843790,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4403,NaN,262300,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区,草莓桑,2021-10-03 21:21,NaN,2022-11-28 12:50:42,269,52.371532,39.092153,8.539312,positive,6818f1ca-8c84-4712-bce5-73f1b42a09a3,金黄的白桦林之间，夕阳照在木质的栅栏和牛羊身上，镀上安静的暖色调，远处的额尔齐斯河静静流淌闪...,可可托海，一个自带BGM的地方，一个中老年朋友听了无不兴奋起来的地方 进入阿勒泰地区的第一天...
4404,NaN,262479,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区,Pachelbel-L,2022-07-13 00:34,NaN,2022-11-28 12:51:36,264,75.650555,7.377163,16.975282,positive,0afd6265-a86f-49ac-818b-94d93183c00e,在挪威的那一个月，真的是我最开心的日子了。每一天都感觉过的有所期待，路过中心教堂，路过鲜花市...,在挪威的那一个月，真的是我最开心的日子了。每一天都感觉过的有所期待，路过中心教堂，路过鲜花市...
4405,NaN,262479,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区,Pachelbel-L,2022-07-13 00:34,NaN,2022-11-28 12:51:36,264,18.675350,43.642849,37.684801,neutral,a5de79c8-c39b-4558-80ac-200f838fc5be,天，看到我疯玩了一身土也不舍得训我，只站在窗口大声喊我“龙崽，回来吃饭咯”。奶奶你要健健康康...,在挪威的那一个月，真的是我最开心的日子了。每一天都感觉过的有所期待，路过中心教堂，路过鲜花市...
4406,NaN,262534,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区,西海岸的杨_,2020-03-01 12:34,NaN,2022-11-28 12:52:04,203,48.100403,36.184034,15.718557,positive,a2a60edd-4b96-46e3-9fe1-4a003cf30b44,终于开始整理去年8月去北疆环游的照片。第一站从可可托海开始。 Day2可可托海 可可托海，哈...,终于开始整理去年8月去北疆环游的照片。第一站从可可托海开始。 Day2可可托海 可可托海，哈...
4407,NaN,262534,伊犁哈萨克自治州阿勒泰地区富蕴可可托海景区,西海岸的杨_,2020-03-01 12:34,NaN,2022-11-28 12:52:04,203,98.709285,1.291889,0.001823,positive,abb46fdd-6323-4f40-b813-c32d9ff4cdd1,满足。,终于开始整理去年8月去北疆环游的照片。第一站从可可托海开始。 Day2可可托海 可可托海，哈...

In [192]:
data_over_15.to_csv('comments_over_15.csv')
print('comments_over_15.csv is completed!')

comments_over_15.csv is completed!

In [198]:
count = 0
for item in data_over_15:
    if item['comment_detail'].isnull:
        count +=1
count

TypeError: string indices must be integers

In [9]:
data_new

,comment_id,scence_name,user_name,comment_time,comment_detail,crawl_time,count_1,comment_len
0,1451,圆明园,小桃枝枝,2022-11-25 17:50,明天就要降温了今天风好大,2022-11-25 21:10:47,1,12
1,1452,圆明园,繁星-满空,2022-11-25 19:29,这样能封一辈子吗病毒没死几个人防疫倒是快把人折磨死了,2022-11-25 21:10:47,1,26
2,1453,圆明园,Ronnie-Osullivan,2022-11-25 11:11,圆明园被烧十二年后长春园西洋楼花园门残影摄于公元1873同治十二年,2022-11-25 21:10:47,1,33
3,1454,圆明园,白雪皑皑银装素裹分外妖娆,2022-11-25 14:55,分享图片,2022-11-25 21:10:47,1,4
4,1455,圆明园,在学术边缘挣扎,2022-11-25 13:04,吃完饭坐上坐骑真舒服呀,2022-11-25 21:10:47,1,11
...,...,...,...,...,...,...,...,...
259062,267798,湖南省株洲市炎帝陵景区,青春败给了生活,2020-10-03 13:13,不要随便掏心掏肺，保留一部分神秘。 那是你在困境中，唯一能自救的东西。 —— 张皓宸,2022-11-28 13:42:06,1,43
259063,267799,湖南省株洲市炎帝陵景区,Mars-段雄伟,2019-10-05 19:23,一对情侣谈恋爱，总有一个强势的，一个随和的。一个厉害的，一个温顺的。一个勤快的，一个懒惰的。...,2022-11-28 13:42:06,1,182
259064,267800,湖南省株洲市炎帝陵景区,想做一条勇敢的咸鱼,2019-07-24 17:26,,2022-11-28 13:42:06,1,0
259065,267801,湖南省株洲市炎帝陵景区,制造精彩,2019-10-24 18:12,别有洞天,2022-11-28 13:42:06,1,4
259066,267802,湖南省株洲市炎帝陵景区,pandaweily,2019-08-16 13:18,分享图片,2022-11-28 13:42:06,1,4

# 计算每天每个地方的微博数

In [13]:
def top10words(string1):
    string2 = string1[:11]
    return string2

In [14]:
data_new['comment_day'] = data_new['comment_time'].apply(top10words)
data_new['comment_day']

0          2022-11-25
1          2022-11-25
2          2022-11-25
3          2022-11-25
4          2022-11-25
             ...
259062     2020-10-03
259063     2019-10-05
259064     2019-07-24
259065     2019-10-24
259066     2019-08-16
Name: comment_day, Length: 259067, dtype: object

In [25]:
data_commentNum_perPlacePerDay = data_new.groupby(['comment_day','scence_name']).agg({'count_1':'sum'})
data_commentNum_perPlacePerDay.to_csv('E:\\论文\\第二篇论文\\每天每地的微博数量.csv',encoding = 'utf-8-sig')

In [21]:
data_commentNum_perPlacePerDay.index

MultiIndex([(' 2018-04-08',    ' 四川省雅安市碧峰峡旅游景区'),
            (' 2018-04-11',        ' 毕节市百里杜鹃景区'),
            (' 2018-09-27',         ' 保定市白石山景区'),
            (' 2018-09-27', ' 内蒙古自治区阿拉善盟胡杨林旅游区'),
            (' 2018-09-27',  ' 辽宁省盘锦市红海滩风景廊道景区'),
            (' 2018-09-27',    ' 鄂尔多斯市成吉思汗陵旅游区'),
            (' 2018-09-28', ' 内蒙古自治区阿拉善盟胡杨林旅游区'),
            (' 2018-09-28',         ' 唐山市清东陵景区'),
            (' 2018-09-28',      ' 河北省保定市清西陵景区'),
            (' 2018-09-28',  ' 辽宁省盘锦市红海滩风景廊道景区'),
            ...
            (' 2022-11-28',         ' 乐山市峨眉山景区'),
            (' 2022-11-28',        ' 南宁市青秀山旅游区'),
            (' 2022-11-28',    ' 大理市崇圣寺三塔文化旅游区'),
            (' 2022-11-28',      ' 惠州市惠州西湖旅游景区'),
            (' 2022-11-28',       ' 昆明市昆明世博园景区'),
            (' 2022-11-28',          ' 桂林市漓江景区'),
            (' 2022-11-28',        ' 毕节市百里杜鹃景区'),
            (' 2022-11-28',        ' 酉阳桃花源旅游景区'),
            (' 2022-11-28',    ' 长沙市岳麓山·橘子洲旅游区'),
            (' 2022-11-28', ' 阿坝藏族羌族自治州九寨沟旅游景区')],
           names=['comment_day', 'scence_name'], length=99128)

KeyError: ('comment_day', 'scence_name')

In [22]:
def tenwords(string1):
    return string1[:10]
data_ajust_merge['comment_time1'] = data_ajust_merge['comment_time'].apply(tenwords)
data_ajust_merge

,comment_id,comment_detail_x,scence_name,user_name,comment_time,comment_detail_y,crawl_time,comment_len,comment_time1
0,1635,写论文前最后的挣扎十块钱的快乐 真的好喜欢一个人逛公园的感觉见到了红嘴大雁和黑嘴大雁入冬了只...,圆明园,是我啊199408,2022-11-17 16:48,写论文前最后的挣扎十块钱的快乐 真的好喜欢一个人逛公园的感觉见到了红嘴大雁和黑嘴大雁入冬了只...,2022-11-25 21:12:00,218,2022-11-17
1,1635,好了手机没电了该回家喽又是美好的一天,圆明园,是我啊199408,2022-11-17 16:48,写论文前最后的挣扎十块钱的快乐 真的好喜欢一个人逛公园的感觉见到了红嘴大雁和黑嘴大雁入冬了只...,2022-11-25 21:12:00,218,2022-11-17
2,1662,吴昌硕花卉册页欣赏 吴昌硕绘画的题材以花卉为主亦偶作山水前期得到任颐指点后又参用赵之谦画法并...,圆明园,古今画藏,2022-11-14 22:25,吴昌硕花卉册页欣赏 吴昌硕绘画的题材以花卉为主亦偶作山水前期得到任颐指点后又参用赵之谦画法并...,2022-11-25 21:12:00,287,2022-11-14
3,1662,白喜取之字和女字格局或作对角斜势用色上似赵之谦喜用浓丽对比的颜色尤善用西洋红色泽浓艳吴昌硕因...,圆明园,古今画藏,2022-11-14 22:25,吴昌硕花卉册页欣赏 吴昌硕绘画的题材以花卉为主亦偶作山水前期得到任颐指点后又参用赵之谦画法并...,2022-11-25 21:12:00,287,2022-11-14
4,1747,下车后刚进园子没走一会儿就想调头回去空气冷还夹着风穿少了好在太阳没下山一路走着看到有阳光的地...,圆明园,chengyuweiii,2022-11-13 09:10,下车后刚进园子没走一会儿就想调头回去空气冷还夹着风穿少了好在太阳没下山一路走着看到有阳光的地...,2022-11-25 21:12:28,223,2022-11-13
...,...,...,...,...,...,...,...,...,...
7962,267686,。 灵其鉴之，伏惟尚飨。,湖南省株洲市炎帝陵景区,G黄智雄,2020-09-29 08:43,【国家每三年一轮的三皇（黄帝、炎帝、舜帝）大祭，有两个在湖南（炎陵的炎帝、永州的舜帝）。陕西...,2022-11-28 13:41:22,412,2020-09-29
7963,267732,第一次来炎帝陵拜祭 炎帝陵是中华民族始祖炎帝神农氏的安息地。炎帝陵自宋乾德五年（967年）...,湖南省株洲市炎帝陵景区,洪山竹海2022,2020-10-02 16:19,第一次来炎帝陵拜祭 炎帝陵是中华民族始祖炎帝神农氏的安息地。炎帝陵自宋乾德五年（967年）...,2022-11-28 13:41:50,212,2020-10-02
7964,267732,山、山西高平、河南柘城。,湖南省株洲市炎帝陵景区,洪山竹海2022,2020-10-02 16:19,第一次来炎帝陵拜祭 炎帝陵是中华民族始祖炎帝神农氏的安息地。炎帝陵自宋乾德五年（967年）...,2022-11-28 13:41:50,212,2020-10-02
7965,267743,2021.09.24，湖南-株洲市（湘B）-炎陵县-炎帝陵。突然想到了两点：第一，去黄帝陵的...,湖南省株洲市炎帝陵景区,Missummer1985,2021-10-02 16:39,2021.09.24，湖南-株洲市（湘B）-炎陵县-炎帝陵。突然想到了两点：第一，去黄帝陵的...,2022-11-28 13:41:50,336,2021-10-02
7966,267743,耀邦同时一道来过这里，景区里有这个珍贵的老照片。每年都有很多海外华人回来祭祖！ 阪泉之战：黄...,湖南省株洲市炎帝陵景区,Missummer1985,2021-10-02 16:39,2021.09.24，湖南-株洲市（湘B）-炎陵县-炎帝陵。突然想到了两点：第一，去黄帝陵的...,2022-11-28 13:41:50,336,2021-10-02

In [24]:
data_ajust_merge1 = data_ajust_merge[['comment_id','comment_time']]

In [25]:
data_new_less_2001 = data_new_less_200[['comment_id','comment_time']]

In [28]:
df_1 = pd.concat([data_ajust_merge1, data_new_less_2001],axis = 0)

In [37]:
df_1

        comment_id      comment_time
0             1635  2022-11-17 16:48
1             1635  2022-11-17 16:48
2             1662  2022-11-14 22:25
3             1662  2022-11-14 22:25
4             1747  2022-11-13 09:10
...            ...               ...
259061      267797  2019-03-01 13:34
259062      267798  2020-10-03 13:13
259063      267799  2019-10-05 19:23
259065      267801  2019-10-24 18:12
259066      267802  2019-08-16 13:18

[241516 rows x 2 columns]

In [39]:
df_1.to_csv('E:\\论文\\第二篇论文\\截止到2023年2月数据汇总\\前数据1.csv',encoding = 'utf-8-sig')